name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Enable Flutter Web
        run: flutter config --enable-web

      - name: Build Flutter Web
        run: |
          flutter build web --release
          touch build/web/.nojekyll  # Add .nojekyll file

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          destination_dir: ./
          force_orphan: true  # Clean branch